const initialState = 
    [
      { id:1 ,
        name: 'MacBook-new',
        category: 'electronics',
        price:"800",
        inStock: 5,
        inCart: 1,
        image: 'https://i.picsum.photos/id/48/5184/3456.jpg?hmac=CqGbzLpjn6uemZM1G8hAgGDefnyntx41HEPKtlK4CDA',
      },
      {id:3,
        name: 'Camera',
        category: 'electronics', 
        price: 99.00,
        inStock: 6,
        inCart: 1,
        image: 'https://i.picsum.photos/id/250/4928/3264.jpg?hmac=4oIwzXlpK4KU3wySTnATICCa4H6xwbSGifrxv7GafWU',
      },
      {id:4,
        name: 'Ipod',
        category: 'electronics',
        price: 299.00,
        inStock: 8,
        inCart: 1,
        image: 'https://i.picsum.photos/id/367/4928/3264.jpg?hmac=H-2OwMlcYm0a--Jd2qaZkXgFZFRxYyGrkrYjupP8Sro',
      },
      {id:5,
        name: 'Joystick',
        category: 'electronics',
        price: 69.00,
        inStock: 12,
        inCart: 1,
        image: 'https://i.picsum.photos/id/96/4752/3168.jpg?hmac=KNXudB1q84CHl2opIFEY4ph12da5JD5GzKzH5SeuRVM',
      },
      {id:6,
        name: 'Phone',
        category: 'electronics',
        price: 999.00,
        inStock: 15,
        inCart: 1,
        image: 'https://i.picsum.photos/id/816/5760/3840.jpg?hmac=GGGDK83mK-OK5SsyNiB45tGIw09LTRaz41c-lmyltDs',
      },
    
    
      {id:8,
        name: 'Burger',
        category: 'food',
        price: 6.39,
        inStock: 90,
        inCart: 1,
        image: 'https://img.freepik.com/premium-photo/big-hamburger-with-double-beef-french-fries_252907-8.jpg?w=2000',
      }, 
         {id:9,
        name: 'Pizza',
        category: 'food',
        price: 5.00,
        inStock: 20,
        inCart: 1,
        image: 'https://images6.alphacoders.com/738/thumb-1920-738359.jpg',
      },   
         {id:5,
        name: 'Robian with Rice',
        category: 'food',
        price: 6.50,
        inStock: 50,
        inCart: 1,
        image: 'https://img.freepik.com/premium-photo/rice-with-young-green-peas-shrimps-arugula-black-bowl-healthy-food-buddha-bowl_2829-2420.jpg?w=2000',
      },
            {id:1,
        name: 'Pasta',
        category: 'food',
        price: 2.39,
        inStock: 33, 
        inCart: 1,
        image: 'https://c.ndtvimg.com/2020-04/dih4ifhg_pasta_625x300_22_April_20.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=886',
      },
      {id:2,
        name: 'Chicken',
        category: 'food',
        price: 3.99,
        inStock: 90,
        inCart: 1,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6NMRD1rufN1GQi_x_dZrB-h-8OcOldgnrbA&usqp=CAU',
      },
      {id:1,
        name: 'Dress',
        category: 'fashion',
        price: 80,
        inStock: 30,
        inCart: 1,
        image: 'http://johnlewis.scene7.com/is/image/JohnLewis/006084491alt8?',
      },
      {id:2,
        name: 'Top',
        category: 'fashion',
        price: 77.95,
        inStock: 30,
        inCart: 1,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtN_OUKXOPnNFytF_9Ym02NEXFnQjBTKckgA&usqp=CAU',
      },
      {id:3,
        name: 'Skirt',
        category: 'fashion',
        price: 25.95,
        inStock: 30,
        inCart: 1,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcdazO-A2GATjul_WcjGUyqN5jKL6E8Fqy5w&usqp=CAU',
      },
      {id:4,
        name: 'Long Sleeve Casual Shirt',
        category: 'fashion',
        price: 35.95,
        inStock: 30,
        inCart: 1,
        image: 'https://static-01.daraz.com.bd/p/716ed67243203d728ab8b0d7c66eb7e1.jpg',
      },
      {id:5,
        name: 'Jeans & Denim',
        category: 'fashion',
        price: 45.95,
        inStock: 30,
        inCart: 1,
        image: 'https://www.benetton.com/dw/image/v2/BBSF_PRD/on/demandware.static/-/Sites-ucb-master/default/dwf98f3ac2/images/Full_Card_v/Benetton_22P_4YO7DF004_901_F_Full_Card_v.jpg?sw=960&sh=1280',
      },
      {id:1,
        name: 'مالا نبوح به',
        category: 'books',
        price: 15.95,
        inStock: 30,
        inCart: 1,
        image: 'https://www.tolaitila.com/images/books/%D9%85%D8%A7-%D9%84%D8%A7-%D9%86%D8%A8%D9%88%D8%AD-%D8%A8%D9%87.jpg',
      },
      {id:1,
        name: 'أنت لي',
        category: 'books',
        price: 20.95,
        inStock: 30,
        inCart: 1,
        image: 'https://play-lh.googleusercontent.com/AXohDOXSk3Drt7UAPEC_4xea9R2mcKOl_jPXI-Q5eqbxHLjprJ3qYtB3NpUFhzJNqOI',
      },
      {id:1,
        name: 'صاحب الظل الطويل',
        category: 'books',
        price: 15.95,
        inStock: 30,
        inCart: 1,
        image: 'https://books-library.net/files/books-library.online-1562961552-931.jpg',
      },
    ];


export default (state = initialState, action) => {
  const { type, payload } = action;
  switch (type) {
  case 'addToCart':
    return state.map(product => {
      if(product.name === payload.name){
        return {...product, inStock: product.inStock - 1};
      }else{
        return product;
      }
    });


  default:
    return state;
  }
};

